//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devnet_1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Devnet_1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %PDF-1.7        ///%����
        ///150 0 obj        ///&lt;&lt;/Linearized 1/L 397732/O 152/E 194722/N 8/T 397159/H [ 594 375]&gt;&gt;        ///endobj        ///             
        ///193 0 obj        ///&lt;&lt;/DecodeParms&lt;&lt;/Columns 5/Predictor 12&gt;&gt;/Filter/FlateDecode/ID[&lt;91A41FA06E83E4B71D1FD265B7C4D35D&gt;&lt;6EBDC8B135DD0B40BC906519F40E438A&gt;]/Index[150 74]/Info 149 0 R/Length 165/Prev 397160/Root 151 0 R/Size 224/Type/XRef/W[1 3 1]&gt;&gt;stream
        ///h�bbd```b``�	&quot;w�Im�Z	&quot;�n�El�d$�d����&quot;� ���d��b�F�ş�IM�&quot;���&quot;�&amp;$��w��ĀH��]�`�&apos;X�7�|1�-A�#�        ///q[
        ///�|���$c,�d�����2$�0�8���	4�`�10�?� [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inputpdf {
            get {
                return ResourceManager.GetString("inputpdf", resourceCulture);
            }
        }
    }
}
